### ISSUE TITLE
Issue compiling CarveLibWrapper Project

### ISSUE THREAD

**Issue by ThinkingInXyZ** [Maghoumi/CarveSharp#2]
Hello

First of all, thanks for the work. Very nice. I am trying to compile your project but i am getting some errors while compiling the project CarveLibWrapper.  I am using Visual Studio 2017.  Any idea? 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) char const * __cdecl std::_Winerror_map(int)" (__imp_?_Winerror_map@std@@YAPEBDH@Z)	CarveLibWrapper	C:\Users\ting\Downloads\CarveSharp-master\CarveSharp-master\CarveLibWrapper\carvelib.lib(triangulator.obj)	1	

```

**Comment by Maghoumi** [comment]
@ThinkingInXyZ Thanks for your interest. As mentioned in #1 and also the bottom of the readme file, the project is targeted towards Visual Studio 2013. Since the library file of Carve was compiled using VS 2013 and included in the project, it seems to me that that binary file is not compatible with other VS versions.

A few months ago, I tried building a (new?) version of Carve (https://github.com/VTREEM/Carve) for VS 2015. There were some fixes needed to enable the build which are available in my fork of that project (https://github.com/Maghoumi/Carve).

Although the build succeeded, I couldn't get any examples to work (most of them threw segmentation faults). So I didn't explore that path any further.

At this point, if you can afford to use Visual Studio 2013, you can use CarveSharp without any issues. Otherwise you are more than welcome to either build sybren-carve (https://github.com/azarus/sybren-carve) with VS 2017 and send me a pull request to update the project, or try and get the other Carve fork (https://github.com/Maghoumi/Carve) to work with VS 2017 and rebuild the C# project in VS 2017.
